### ISSUE TITLE
jb init crashes

### ISSUE THREAD

**Issue by frankgerhardt** [akoenig/jutebag#1]
I followed the instructions but I get an error when running jb init. 
I'm using Ubunt 12.04 with the latest node.
# :~$ sudo npm install -g jutebag

[sudo] password for siena: 
npm http GET https://registry.npmjs.org/jutebag
npm http 304 https://registry.npmjs.org/jutebag
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/coffee-script
npm http GET https://registry.npmjs.org/node-pocket
npm http GET https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/underscore
npm http 304 https://registry.npmjs.org/node-pocket
npm http 304 https://registry.npmjs.org/coffee-script
npm http 200 https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http 200 https://registry.npmjs.org/colors/-/colors-0.6.0-1.tgz
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/keypress
npm http 304 https://registry.npmjs.org/request
npm http 200 https://registry.npmjs.org/keypress
npm http GET https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http GET https://registry.npmjs.org/form-data
npm http GET https://registry.npmjs.org/mime
npm http GET https://registry.npmjs.org/hawk
npm http GET https://registry.npmjs.org/node-uuid
npm http GET https://registry.npmjs.org/cookie-jar
npm http GET https://registry.npmjs.org/aws-sign
npm http GET https://registry.npmjs.org/oauth-sign
npm http GET https://registry.npmjs.org/forever-agent
npm http GET https://registry.npmjs.org/tunnel-agent
npm http GET https://registry.npmjs.org/json-stringify-safe
npm http GET https://registry.npmjs.org/qs
npm http 200 https://registry.npmjs.org/keypress/-/keypress-0.1.0.tgz
npm http 304 https://registry.npmjs.org/mime
npm http 304 https://registry.npmjs.org/node-uuid
npm http 304 https://registry.npmjs.org/form-data
npm http 304 https://registry.npmjs.org/hawk
npm http 304 https://registry.npmjs.org/aws-sign
npm http 304 https://registry.npmjs.org/oauth-sign
npm http 304 https://registry.npmjs.org/cookie-jar
npm WARN package.json aws-sign@0.2.0 No README.md file found!
npm WARN package.json oauth-sign@0.2.0 No README.md file found!
npm WARN package.json cookie-jar@0.2.0 No README.md file found!
npm http 304 https://registry.npmjs.org/forever-agent
npm WARN package.json forever-agent@0.2.0 No README.md file found!
npm http 304 https://registry.npmjs.org/tunnel-agent
npm http 304 https://registry.npmjs.org/json-stringify-safe
npm WARN package.json tunnel-agent@0.2.0 No README.md file found!
npm http 304 https://registry.npmjs.org/qs
npm WARN engine hawk@0.10.2: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http GET https://registry.npmjs.org/combined-stream
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/boom
npm http GET https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/sntp
npm http GET https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/async
npm http 304 https://registry.npmjs.org/hoek
npm http 304 https://registry.npmjs.org/combined-stream
npm http 304 https://registry.npmjs.org/cryptiles
npm http GET https://registry.npmjs.org/delayed-stream/0.0.5
npm http 304 https://registry.npmjs.org/sntp
npm http 304 https://registry.npmjs.org/boom
npm WARN engine hoek@0.7.6: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine cryptiles@0.1.3: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine sntp@0.1.4: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm WARN engine boom@0.3.8: wanted: {"node":"0.8.x"} (current: {"node":"v0.10.3","npm":"1.2.17"})
npm http 304 https://registry.npmjs.org/delayed-stream/0.0.5
/usr/bin/jb -> /usr/lib/node_modules/jutebag/bin/jutebag
jutebag@0.3.0 /usr/lib/node_modules/jutebag
├── colors@0.6.0-1
├── underscore@1.4.4
├── coffee-script@1.6.2
├── commander@1.1.1 (keypress@0.1.0)
└── node-pocket@0.9.4 (request@2.16.6)
# :~$ jb init

/usr/lib/node_modules/jutebag/index.js:47
        jutebag.commands.init.exec();
                              ^
TypeError: Cannot call method 'exec' of undefined
    at /usr/lib/node_modules/jutebag/index.js:47:31
    at Object.<anonymous> (/usr/lib/node_modules/jutebag/index.js:51:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/lib/node_modules/jutebag/bin/jutebag:5:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3

**Comment by akoenig** [comment]
Hey,

thanks for reporting this issue, but I'm not able to reproduce the problem. I also installed a fresh Ubuntu 12.04 in my VM, but, well, it works.

The only difference I see so far is the installation path. In my environment the module was installed into:

```
/usr/local/lib/node_modules/jutebag/
```

Do have problems with any other module?

/André

**Comment by palisir** [comment]
Exactly same problem here on Mac OS 10.9.1 / npm 1.3.8 / node 0.10.7

**Comment by shedali** [comment]
Reproduced Mac OS 10.9.1 / npm 1.3.24 / node 0.10.25

**Comment by bartlibert** [comment]
Reproduced on Debian jessie/sid / npm 1.4.4 / node 0.10.26

**Comment by nilbus** [comment]
This only occurs when `~/.jutebag/config.json` does not exist, or in other words, if you haven't already run `init`.

**Comment by nilbus** [comment]
I opened pull request #3 to fix this.
